In [2]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\administrator\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\administrator\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\administrator\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\administrator\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\administrator\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\administrator\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd

In [4]:
data=pd.read_csv("retail supermarket - retail supermarket.csv")
data

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,25.2480,3,0.20,4.1028
9990,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,91.9600,2,0.00,15.6332
9991,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,258.5760,2,0.20,19.3932
9992,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,29.6000,4,0.00,13.3200
9993,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,243.1600,2,0.00,72.9480

#### 1- Find record if Sales greater than 500 and Quantity greater than 5?

In [58]:
data[(data["Sales"]>500)& (data["Quantity"]>5)].shape[0]

431

#### 2- Find records if Discount is more than 0.5 (50%) or Profit is negative.

In [57]:
data[(data["Discount"]>0.5)|(data['Profit'] <0)].shape[0]

1871

#### 3- Display Ship Mode and Profit columns if region is East using loc

In [59]:
data.loc[data["Region"] == "East", ["Ship Mode", "Profit"]]

           Ship Mode     Profit
23      Second Class    -1.0196
27    Standard Class -1665.0522
28    Standard Class    -7.0532
29    Standard Class    15.5250
30    Standard Class     1.1016
...              ...        ...
9968  Standard Class   331.1910
9969  Standard Class     6.5975
9981     First Class     5.3690
9984  Standard Class    15.1200
9985  Standard Class    16.1240

[2848 rows x 2 columns]

#### 4- How many records belong to the "Corporate" segment and the "Central" region?

In [60]:
data[(data['Segment']=='Corporate')&(data['Region']=="Central")].shape[0]

673

#### 5- Find all orders in the "Furniture" category but not in "Chairs" sub-category.

In [43]:
data[(data['Category']=='Furniture' )&(data['Sub-Category'] != 'Chairs')]

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
5,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,48.8600,7,0.00,14.1694
10,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,1706.1840,9,0.20,85.3092
24,Standard Class,Consumer,United States,Orem,Utah,84057,West,Furniture,Tables,1044.6300,3,0.00,240.2649
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9962,First Class,Home Office,United States,Houston,Texas,77041,Central,Furniture,Bookcases,383.4656,4,0.32,-67.6704
9964,Second Class,Corporate,United States,Newark,Delaware,19711,East,Furniture,Furnishings,13.4000,1,0.00,6.4320
9980,Second Class,Consumer,United States,Lafayette,Louisiana,70506,South,Furniture,Tables,85.9800,1,0.00,22.3548
9989,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,25.2480,3,0.20,4.1028
9990,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,91.9600,2,0.00,15.6332

#### 6- Which orders have discount (>0.3) and still earned profit (>0)?

In [61]:
data[(data["Discount"]>0.3)&(data['Profit']>0)]

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
343,Second Class,Corporate,United States,Philadelphia,Pennsylvania,19140,East,Technology,Phones,71.928,12,0.4,8.3916
614,Second Class,Consumer,United States,Grove City,Ohio,43123,East,Technology,Phones,119.940,10,0.4,15.9920
986,Standard Class,Home Office,United States,Pasadena,Texas,77506,Central,Technology,Machines,336.510,3,0.4,44.8680
1233,First Class,Corporate,United States,Cincinnati,Ohio,45231,East,Technology,Copiers,839.988,2,0.4,69.9990
1679,Standard Class,Corporate,United States,Philadelphia,Pennsylvania,19134,East,Technology,Phones,32.382,3,0.4,4.3176
1912,Second Class,Corporate,United States,Houston,Texas,77041,Central,Technology,Machines,597.132,3,0.4,49.7610
1986,First Class,Consumer,United States,Columbus,Ohio,43229,East,Technology,Copiers,1439.976,4,0.4,191.9968
2125,Standard Class,Home Office,United States,Philadelphia,Pennsylvania,19143,East,Technology,Phones,62.958,7,0.4,9.4437
2135,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19134,East,Technology,Phones,94.920,4,0.4,15.8200
2728,First Class,Consumer,United States,Toledo,Ohio,43615,East,Technology,Phones,629.958,7,0.4,94.4937
3781,Second Class,Consumer,United States,Philadelphia,Pennsylvania,19120,East,Technology,Phones,269.982,3,0.4,40.4973
4003,Standard Class,Consumer,United States,San Antonio,Texas,78207,Central,Technology,Machines,287.910,3,0.4,33.5895
4491,Second Class,Consumer,United States,Columbus,Ohio,43229,East,Technology,Copiers,659.988,2,0.4,109.9980
4812,Second Class,Consumer,United States,Philadelphia,Pennsylvania,19134,East,Technology,Copiers,1199.976,4,0.4,179.9964
5384,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19143,East,Technology,Phones,358.200,3,0.4,41.7900
5385,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19143,East,Technology,Phones,545.916,14,0.4,72.7888
6425,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19120,East,Technology,Copiers,8399.976,4,0.4,1119.9968
6951,Standard Class,Corporate,United States,Dallas,Texas,75217,Central,Technology,Machines,479.988,2,0.4,55.9986
7042,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19134,East,Technology,Copiers,599.970,5,0.4,69.9965
8123,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19134,East,Technology,Copiers,1079.976,4,0.4,125.9972
8799,First Class,Consumer,United States,Philadelphia,Pennsylvania,19134,East,Technology,Copiers,1799.970,5,0.4,239.9960
8808,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19134,East,Technology,Phones,118.650,5,0.4,19.7750
9106,Standard Class,Consumer,United States,Houston,Texas,77041,Central,Technology,Machines,287.910,3,0.4,33.5895
9516,Second Class,Consumer,United States,Bowling Green,Ohio,43402,East,Technology,Phones,26.982,3,0.4,4.0473
9617,Standard Class,Corporate,United States,Bowling Green,Ohio,43402,East,Technology,Copiers,899.982,3,0.4,74.9985
9798,Standard Class,Corporate,United States,Toledo,Ohio,43615,East,Technology,Phones,26.376,4,0.4,2.6376

#### 7- Find high-profit orders where Quantity > 5 and Category == 'Technology'.

In [64]:
data[(data["Profit"] > 0) &(data["Quantity"] > 5) &(data["Category"] == "Technology")]

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
7,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,907.152,6,0.2,90.7152
35,First Class,Corporate,United States,Richardson,Texas,75080,Central,Technology,Phones,1097.544,7,0.2,123.4737
106,Standard Class,Consumer,United States,Charlotte,North Carolina,28205,South,Technology,Accessories,74.112,8,0.2,17.6016
123,First Class,Consumer,United States,Wilmington,Delaware,19805,East,Technology,Phones,68.040,7,0.0,19.7316
147,Standard Class,Corporate,United States,Franklin,Wisconsin,53132,Central,Technology,Phones,384.450,11,0.0,103.8015
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9840,Standard Class,Consumer,United States,Long Beach,California,90805,West,Technology,Phones,44.736,8,0.2,4.4736
9882,First Class,Consumer,United States,Woodstock,Georgia,30188,South,Technology,Accessories,272.610,13,0.0,98.1396
9891,Second Class,Corporate,United States,Milwaukee,Wisconsin,53209,Central,Technology,Accessories,124.250,7,0.0,48.4575
9895,Standard Class,Consumer,United States,Chicago,Illinois,60623,Central,Technology,Accessories,153.824,11,0.2,38.4560
9941,Standard Class,Consumer,United States,San Francisco,California,94122,West,Technology,Accessories,223.580,14,0.0,87.1962

#### 8- Select rows 0–4 and columns 'Ship Mode', 'Segment', 'Sales' by position using iloc

In [67]:
data.iloc[[0,1,2,3,4],[0,1,9]]

        Ship Mode    Segment     Sales
0    Second Class   Consumer  261.9600
1    Second Class   Consumer  731.9400
2    Second Class  Corporate   14.6200
3  Standard Class   Consumer  957.5775
4  Standard Class   Consumer   22.3680

#### 9- Show Home Office segment orders with Sales > 1000 and Quantity > 3.

In [68]:
data[(data['Segment']=='Home Office')&(data['Sales']>1000)&(data['Quantity']>3)]

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
244,Second Class,Home Office,United States,Lakeville,Minnesota,55044,Central,Furniture,Chairs,2001.860,7,0.0,580.5394
247,Second Class,Home Office,United States,Lakeville,Minnesota,55044,Central,Office Supplies,Appliances,1503.250,5,0.0,496.0725
353,First Class,Home Office,United States,New York City,New York,10009,East,Office Supplies,Binders,4355.168,4,0.2,1415.4296
463,Standard Class,Home Office,United States,Phoenix,Arizona,85023,West,Furniture,Tables,1272.630,6,0.5,-814.4832
515,Standard Class,Home Office,United States,Great Falls,Montana,59405,West,Technology,Copiers,2999.950,5,0.0,1379.9770
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8890,Second Class,Home Office,United States,Columbia,Missouri,65203,Central,Office Supplies,Appliances,1927.590,7,0.0,751.7601
8892,Standard Class,Home Office,United States,San Diego,California,92037,West,Furniture,Chairs,2676.672,9,0.2,267.6672
9056,First Class,Home Office,United States,New York City,New York,10011,East,Furniture,Chairs,2621.322,11,0.1,553.3902
9660,Standard Class,Home Office,United States,Santa Barbara,California,93101,West,Technology,Phones,3023.928,9,0.2,226.7946
9673,Standard Class,Home Office,United States,Philadelphia,Pennsylvania,19143,East,Technology,Phones,1499.970,5,0.4,-374.9925

#### 10- Find orders where Profit Margin > 0.3
##### Profit Margin = (Profit/Sales)

In [70]:
data.loc[(data["Profit"] / data["Sales"]) > 0.3]

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.620,2,0.0,6.8714
8,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,18.504,3,0.2,5.7825
12,Standard Class,Consumer,United States,Concord,North Carolina,28027,South,Office Supplies,Paper,15.552,3,0.2,5.4432
13,Standard Class,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Binders,407.976,3,0.2,132.5922
20,Second Class,Consumer,United States,San Francisco,California,94109,West,Office Supplies,Binders,22.720,4,0.2,7.3840
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9982,Standard Class,Consumer,United States,Grand Rapids,Michigan,49505,Central,Office Supplies,Paper,35.560,7,0.0,16.7132
9984,Standard Class,Consumer,United States,Long Beach,New York,11561,East,Office Supplies,Labels,31.500,10,0.0,15.1200
9986,Standard Class,Consumer,United States,Los Angeles,California,90008,West,Technology,Accessories,36.240,1,0.0,15.2208
9987,Standard Class,Corporate,United States,Athens,Georgia,30605,South,Technology,Accessories,79.990,1,0.0,28.7964
9992,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,29.600,4,0.0,13.3200